// 数据池
export const ADD_POOL = 'ADD_POOL'
export const UPDATE_POOL_STATE = 'UPDATE_POOL_STATE'
export const UPDATE_POOL_FOCUS = 'UPDATE_POOL_FOCUS'
export const ADD_POOL_DETAIL = 'ADD_POOL_DETAIL'
export const DATA_MODULE_FOCUS_SUCCESS = 'DATA_MODULE_FOCUS_SUCCESS'
export const DATA_MODULE_FOCUS_FAILURE = 'DATA_MODULE_FOCUS_FAILURE'
export const UPDATE_TASK_STATE_SUCCESS = 'UPDATE_TASK_STATE_SUCCESS'
export const DATA_MODULE_RECOMMEND_USERFUL = 'DATA_MODULE_RECOMMEND_USERFUL'
